var surveyName="",pageBody=document.querySelector("body"),pageCheck=function(){if("surveyPage"===pageBody.className){localStorage.clear();var a=document.querySelector("#iniSurvey"),g=document.querySelector("#hiddenForm"),c=document.querySelector("#bbiQuestions");g.style.visibility="hidden";a.addEventListener("click",function(b){g.style.visibility="hidden"===g.style.visibility?"visible":"hidden"});c.addEventListener("submit",function(b){b.preventDefault();"click to choose an option..."===b.target.elements.inputImpAttrib.value?
alert("You obviously missed an option Meatbag! Give me your data!"):("Random"===b.target.elements.inputImpAttrib.value&&(b.target.elements.inputImpAttrib.value=getRandom(randBusinessGoal)),surveyName="First Name: "+b.target.elements.fName.value,startCon="Startup Concept: "+b.target.elements.inputBusType4.value,startConClean=b.target.elements.inputBusType4.value,triggerWord="Startup Trigger Word: "+b.target.elements.inputFreud.value,triggerClean=b.target.elements.inputFreud.value,startUpAttrib="Important Startup Attribute: "+
b.target.elements.inputImpAttrib.value,startAttribClean=b.target.elements.inputImpAttrib.value,localStorage.setItem("First Name",surveyName.trim()),localStorage.setItem("Startup Concept",startCon.trim()),localStorage.setItem("Startup Concept Clean",startConClean.trim()),localStorage.setItem("Trigger",triggerWord.trim()),localStorage.setItem("Trigger Clean",triggerClean.trim()),localStorage.setItem("Startup Attribute",startUpAttrib.trim()),localStorage.setItem("Startup Attribute Clean",startAttribClean.trim()),
window.location="results.html")})}else if("mainPageBody"===pageBody.className){var l="";a=generateBullets();console.log(a);document.querySelector("#liOne").innerHTML=a[0];document.querySelector("#liTwo").innerHTML=a[1];document.querySelector("#liThree").innerHTML=a[2];var h=document.querySelector("#instaForm");a=document.querySelector("#instaClose");var k=document.querySelector("#instaDismiss"),m=document.querySelector("#instaSub");h.addEventListener("submit",function(b){b.preventDefault();localStorage.setItem("Quick Tag",
b.target.elements.instaInput.value);l=quantumBBI();h.reset();h.remove();m.remove();k.style.display="none";document.getElementById("instaP").textContent="";document.getElementById("statusBar").style.display="";document.getElementById("barContSpace").style.display="";document.getElementById("statText").textContent=getRandom(loadArray);setTimeout(function(){document.getElementById("statusBar").style.display="none";k.style.display="";document.getElementById("instaP").textContent=l},2E3)});a.addEventListener("click",
function(b){localStorage.clear();"Enter your startup idea tag or trigger word..."!=document.getElementById("instaP").innerHTML&&history.go(0)});k.addEventListener("click",function(b){localStorage.clear();"Enter your startup idea tag or trigger word..."!=document.getElementById("instaP").innerHTML&&history.go(0)})}else if("resultsPage"===pageBody.className){a=localStorage.getItem("First Name");c=localStorage.getItem("Startup Concept");var d=localStorage.getItem("Trigger"),e=localStorage.getItem("Startup Attribute");
document.querySelector("#result1").textContent=a;document.querySelector("#result2").textContent=c;document.querySelector("#result3").textContent=d;document.querySelector("#result4").textContent=e;a=a.split(":");c=c.split(":");d=d.split(":");e=e.split(":");a=a[1];c=c[1];d=d[1];e=e[1];var n=getRandom(hateYourNameArray),p=getRandom(hateYourStartUpArray),q=getRandom(triggerJudgementArray),r=getRandom(businessGoalJudgement);c="So, your name is "+a+".  That is "+n+" And let's see here.  Your StartUp Idea was "+
c+" "+p+" Your StartUp Trigger word was "+d+". "+q+" Lastly, the most important attribute to your StartUp was "+e+". "+r+" Based on the limited and terrible data you gave me, let us see if I can flesh (get it?) out your Bad Business Idea! ";a=quantumBBI(a);document.querySelector("#conclusionsMashup").textContent=c;document.querySelector("#badBusinessIdea").textContent=a}else if("contactPageBody"===pageBody.className){var t=function(){var b=document.querySelector("#contactFN4").value,a=document.querySelector("#emailType4").value,
c=document.querySelector("#contactCat").value,d=document.querySelector("#contactTags").value,e=document.querySelector("#contactIdeaInput").value,f={Name:b,Email:a,Category:c,TagList:d,BadBusinessIdea:e};f=JSON.stringify(f);console.log(f);""==b||""==a||""==c||""==d||""==e?alert("You need to fill out all fields meatbag..."):$.ajax({type:"POST",url:"form.php",contentType:"application/json",data:f,cache:!1,success:function(){$("#contactSent").modal("show");$("#contactUs")[0].reset()}});return!1};document.querySelector("#contactSubmit").addEventListener("click",
function(){t()});document.querySelector("#sendThank").addEventListener("click",function(){document.location.reload(!0)})}};pageCheck();
